name: Prepare for release

description: Builds, tests, and creates an installer that's ready for release.

inputs:
  version:
    description: 'Version number for the app'
    default: '0.0.0'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4

    - name: Build
      shell: bash
      run: dotnet build

    - name: Test
      shell: bash
      run: dotnet test

    - name: Publish
      shell: bash
      run: dotnet publish ./TeslaCam/TeslaCam.csproj -o "publish" -c Release -r win-x64 --self-contained -p:PublishSingleFile=true /p:Version=${{ inputs.version }}

    - name: Create installer
      shell: bash
      run: |
        dotnet tool install --global wix --version 5.0.1
        wix build Product.wxs -o "publish/Install TeslaCam Player.msi"

    - uses: actions/upload-artifact@v4
      with:
        path: |
          publish
