name: Full Build

description: Builds, tests, and creates binaries that are ready for release.

inputs:
  version:
    description: 'Version number for the app'
    default: '0.0.0'
  archs:
    description: 'Architectures for the build'
    default: 'x64 arm64'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4

    - name: Build
      shell: bash
      run: dotnet build

    - name: Test
      shell: bash
      run: dotnet test

    - name: Create Binaries
      shell: bash
      run: |
        for arch in ${{ inputs.archs }}; do
          dotnet publish ./TeslaCam/TeslaCam.csproj -o "publish/$arch" -c Release -f net9.0-windows --os win --arch $arch --self-contained -p:PublishSingleFile=true -p:Version=${{ inputs.version }}
        done

    - name: Create Portable ZIPs
      shell: pwsh
      run: |
        $archs = "${{ inputs.archs }}".Split(" ")
        foreach ($arch in $archs) {
          Compress-Archive -Path "publish/$arch/*" -DestinationPath "TeslaCamPlayer-${{ inputs.version }}-$arch.zip"
        }

    - uses: actions/upload-artifact@v4
      with:
        path: |
          publish
