name: Prepare for release

description: Builds, tests, and creates an installer that's ready for release.

inputs:
  version:
    description: 'Version number for the app'
    default: '0.0.0'
  rids:
    description: 'Runtime identifiers for the build'
    default: 'win-x64 win-arm64'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4

    - name: Build
      shell: bash
      run: dotnet build

    - name: Test
      shell: bash
      run: dotnet test

    - name: Publish
      shell: bash
      run: |
        for rid in ${{ inputs.rids }}; do
          dotnet publish ./TeslaCam/TeslaCam.csproj -o "publish/$rid" -c Release -f net9.0-windows -r $rid --self-contained -p:PublishSingleFile=true -p:Version=${{ inputs.version }}
        done

    - name: Compress
      shell: pwsh
      run: |
        for rid in ${{ inputs.rids }}; do
          Compress-Archive "publish/$rid/*" "TeslaCamPlayer-${{ inputs.version }}-$rid.zip"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: portable-artifacts
        path: "*.zip"
