name: Release and deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the app'
        required: true
        default: ''

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/actions/full-build
      with:
         version: ${{ github.event.inputs.version }}

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ github.event.inputs.version }}"
        artifacts: "portable.zip"
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: true
        artifactErrorsFailBuild: true
        makeLatest: true
        generateReleaseNotes: true
