name: Release and deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the app'
        required: true
        default: ''
      updateRelease:
        description: 'Update existing release'
        required: true
        default: 'false'

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/actions/full-build
      with:
        version: ${{ github.event.inputs.version }}

    # - name: Remove existing release with the same tag
    #   if: ${{ inputs.updateRelease == 'true' }}
    #   run: |
    #     gh release delete "v${{ github.event.inputs.version }}" --yes || echo "Release not found for this tag"

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        tag: "v${{ github.event.inputs.version }}"
        artifacts: "publish/*.zip"
        generateReleaseNotes: true
        prerelease: ${{ contains(github.event.inputs.version, 'preview') }}
        allowUpdates: ${{ github.event.inputs.updateRelease }}
        removeArtifacts: true
        omitBodyDuringUpdate: true
